### ISSUE TITLE
Lables slanted the wrong way and too long

### ISSUE THREAD

**Issue by kpover** [AlejandroEvolcon/DoubleBarChartForQlikview#1]
![image](https://cloud.githubusercontent.com/assets/8176690/10084432/07f0811e-62c9-11e5-924e-f57e501dc7bb.png)

It would be good if the labels where diagonal up left to right (/) and only showed what fit or you had the option to adjust the label length in the properties.  Also, it would be great to label the y-axis and change the the scale to thousands or millions automatically depending on the maximum value.

Thanks.

**Comment by AlejandroEvolcon** [comment]
Thank you for your comments @kpover, I already made the changes, I hope you find them useful
